// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentManagement.Models;

#nullable disable

namespace StudentManagement.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StudentManagement.Models.DangKyHocPhan", b =>
                {
                    b.Property<int>("MaDK")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDK"));

                    b.Property<double?>("DiemCuoiKy")
                        .HasColumnType("float");

                    b.Property<double?>("DiemQuaTrinh")
                        .HasColumnType("float");

                    b.Property<double?>("DiemTongKet")
                        .HasColumnType("float");

                    b.Property<string>("KetQua")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MaLHP")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MaSV")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("NgayDangKy")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaDK");

                    b.HasIndex("MaLHP");

                    b.HasIndex("MaSV");

                    b.ToTable("DangKyHocPhan");
                });

            modelBuilder.Entity("StudentManagement.Models.DiemSo", b =>
                {
                    b.Property<int>("MaDiem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDiem"));

                    b.Property<double?>("DiemChuyenCan")
                        .HasColumnType("float");

                    b.Property<double?>("DiemCuoiKy")
                        .HasColumnType("float");

                    b.Property<double?>("DiemGiuaKy")
                        .HasColumnType("float");

                    b.Property<double?>("DiemTongKet")
                        .HasColumnType("float");

                    b.Property<string>("MaHK")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MaMH")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MaSV")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("XepLoai")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaDiem");

                    b.HasIndex("MaHK");

                    b.HasIndex("MaMH");

                    b.HasIndex("MaSV");

                    b.ToTable("DiemSo");
                });

            modelBuilder.Entity("StudentManagement.Models.GiangVien", b =>
                {
                    b.Property<string>("MaGV")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("GioiTinh")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HocVi")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MaKhoa")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("MaGV");

                    b.HasIndex("MaKhoa");

                    b.ToTable("GiangVien");
                });

            modelBuilder.Entity("StudentManagement.Models.HocKy", b =>
                {
                    b.Property<string>("MaHK")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("HocKyThu")
                        .HasColumnType("int");

                    b.Property<string>("NamHoc")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenHK")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaHK");

                    b.ToTable("HocKy");
                });

            modelBuilder.Entity("StudentManagement.Models.Khoa", b =>
                {
                    b.Property<string>("MaKhoa")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("TenKhoa")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("MaKhoa");

                    b.ToTable("Khoa");

                    b.HasData(
                        new
                        {
                            MaKhoa = "CNTT",
                            Email = "cntt@university.edu.vn",
                            SoDienThoai = "0123456789",
                            TenKhoa = "Công nghệ thông tin"
                        },
                        new
                        {
                            MaKhoa = "KINHTE",
                            Email = "kinhte@university.edu.vn",
                            SoDienThoai = "0987654321",
                            TenKhoa = "Kinh tế"
                        });
                });

            modelBuilder.Entity("StudentManagement.Models.Lop", b =>
                {
                    b.Property<string>("MaLop")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("KhoaHoc")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MaKhoa")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("SiSo")
                        .HasColumnType("int");

                    b.Property<string>("TenLop")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaLop");

                    b.HasIndex("MaKhoa");

                    b.ToTable("Lop");

                    b.HasData(
                        new
                        {
                            MaLop = "CNTT01",
                            KhoaHoc = "K42",
                            MaKhoa = "CNTT",
                            SiSo = 0,
                            TenLop = "Công nghệ thông tin 01"
                        },
                        new
                        {
                            MaLop = "CNTT02",
                            KhoaHoc = "K42",
                            MaKhoa = "CNTT",
                            SiSo = 0,
                            TenLop = "Công nghệ thông tin 02"
                        },
                        new
                        {
                            MaLop = "KT01",
                            KhoaHoc = "K42",
                            MaKhoa = "KINHTE",
                            SiSo = 0,
                            TenLop = "Kinh tế 01"
                        });
                });

            modelBuilder.Entity("StudentManagement.Models.LopHocPhan", b =>
                {
                    b.Property<string>("MaLHP")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MaGV")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MaHK")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MaMH")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("PhongHoc")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SiSoHienTai")
                        .HasColumnType("int");

                    b.Property<int>("SiSoToiDa")
                        .HasColumnType("int");

                    b.HasKey("MaLHP");

                    b.HasIndex("MaGV");

                    b.HasIndex("MaHK");

                    b.HasIndex("MaMH");

                    b.ToTable("LopHocPhan");
                });

            modelBuilder.Entity("StudentManagement.Models.MonHoc", b =>
                {
                    b.Property<string>("MaMH")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MaKhoa")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MoTa")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("SoTinChi")
                        .HasColumnType("int");

                    b.Property<string>("TenMH")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("MaMH");

                    b.HasIndex("MaKhoa");

                    b.ToTable("MonHoc");
                });

            modelBuilder.Entity("StudentManagement.Models.SinhVien", b =>
                {
                    b.Property<string>("MaSV")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GioiTinh")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MaLop")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("NamNhapHoc")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("MaSV");

                    b.HasIndex("MaLop");

                    b.ToTable("SinhVien");

                    b.HasData(
                        new
                        {
                            MaSV = "SV001",
                            DiaChi = "Hà Nội",
                            Email = "nguyenvana@example.com",
                            GioiTinh = "Nam",
                            HoTen = "Nguyễn Văn A",
                            MaLop = "CNTT01",
                            NamNhapHoc = 2020,
                            NgaySinh = new DateTime(2002, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoDienThoai = "0912345678",
                            TrangThai = true
                        },
                        new
                        {
                            MaSV = "SV002",
                            DiaChi = "TP. Hồ Chí Minh",
                            Email = "tranthib@example.com",
                            GioiTinh = "Nữ",
                            HoTen = "Trần Thị B",
                            MaLop = "CNTT02",
                            NamNhapHoc = 2020,
                            NgaySinh = new DateTime(2002, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoDienThoai = "0923456789",
                            TrangThai = true
                        });
                });

            modelBuilder.Entity("StudentManagement.Models.DangKyHocPhan", b =>
                {
                    b.HasOne("StudentManagement.Models.LopHocPhan", "LopHocPhan")
                        .WithMany("DangKyHocPhans")
                        .HasForeignKey("MaLHP")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentManagement.Models.SinhVien", "SinhVien")
                        .WithMany("DangKyHocPhans")
                        .HasForeignKey("MaSV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LopHocPhan");

                    b.Navigation("SinhVien");
                });

            modelBuilder.Entity("StudentManagement.Models.DiemSo", b =>
                {
                    b.HasOne("StudentManagement.Models.HocKy", "HocKy")
                        .WithMany()
                        .HasForeignKey("MaHK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentManagement.Models.MonHoc", "MonHoc")
                        .WithMany()
                        .HasForeignKey("MaMH")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentManagement.Models.SinhVien", "SinhVien")
                        .WithMany("DiemSos")
                        .HasForeignKey("MaSV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HocKy");

                    b.Navigation("MonHoc");

                    b.Navigation("SinhVien");
                });

            modelBuilder.Entity("StudentManagement.Models.GiangVien", b =>
                {
                    b.HasOne("StudentManagement.Models.Khoa", "Khoa")
                        .WithMany("GiangViens")
                        .HasForeignKey("MaKhoa")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Khoa");
                });

            modelBuilder.Entity("StudentManagement.Models.Lop", b =>
                {
                    b.HasOne("StudentManagement.Models.Khoa", "Khoa")
                        .WithMany("Lops")
                        .HasForeignKey("MaKhoa")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Khoa");
                });

            modelBuilder.Entity("StudentManagement.Models.LopHocPhan", b =>
                {
                    b.HasOne("StudentManagement.Models.GiangVien", "GiangVien")
                        .WithMany("LopHocPhans")
                        .HasForeignKey("MaGV")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StudentManagement.Models.HocKy", "HocKy")
                        .WithMany("LopHocPhans")
                        .HasForeignKey("MaHK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentManagement.Models.MonHoc", "MonHoc")
                        .WithMany("LopHocPhans")
                        .HasForeignKey("MaMH")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GiangVien");

                    b.Navigation("HocKy");

                    b.Navigation("MonHoc");
                });

            modelBuilder.Entity("StudentManagement.Models.MonHoc", b =>
                {
                    b.HasOne("StudentManagement.Models.Khoa", "Khoa")
                        .WithMany()
                        .HasForeignKey("MaKhoa");

                    b.Navigation("Khoa");
                });

            modelBuilder.Entity("StudentManagement.Models.SinhVien", b =>
                {
                    b.HasOne("StudentManagement.Models.Lop", "Lop")
                        .WithMany("SinhViens")
                        .HasForeignKey("MaLop")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Lop");
                });

            modelBuilder.Entity("StudentManagement.Models.GiangVien", b =>
                {
                    b.Navigation("LopHocPhans");
                });

            modelBuilder.Entity("StudentManagement.Models.HocKy", b =>
                {
                    b.Navigation("LopHocPhans");
                });

            modelBuilder.Entity("StudentManagement.Models.Khoa", b =>
                {
                    b.Navigation("GiangViens");

                    b.Navigation("Lops");
                });

            modelBuilder.Entity("StudentManagement.Models.Lop", b =>
                {
                    b.Navigation("SinhViens");
                });

            modelBuilder.Entity("StudentManagement.Models.LopHocPhan", b =>
                {
                    b.Navigation("DangKyHocPhans");
                });

            modelBuilder.Entity("StudentManagement.Models.MonHoc", b =>
                {
                    b.Navigation("LopHocPhans");
                });

            modelBuilder.Entity("StudentManagement.Models.SinhVien", b =>
                {
                    b.Navigation("DangKyHocPhans");

                    b.Navigation("DiemSos");
                });
#pragma warning restore 612, 618
        }
    }
}
